Fixed a startup error reported by Graham Gilbert.
When the app starts up, it throws an error:
```
TypeError: Cannot read property '_id' of undefined
at MandrillSettings.set (collections/MandrillSettings.collection.coffee:35:4)
```

This was because MandrillSettings.set() was assuming there would always be a settings record available.